# Generated by Django 3.2.9 on 2021-12-08 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinyInventoryItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_hash', models.IntegerField()),
                ('description', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('icon', models.CharField(max_length=250)),
                ('has_icon', models.BooleanField()),
                ('flavor_text', models.CharField(max_length=250)),
                ('tier_type', models.IntegerField()),
                ('tier_type_name', models.CharField(max_length=25)),
                ('item_type_name', models.CharField(max_length=50)),
                ('item_type_tier_name', models.CharField(max_length=50)),
                ('bucket_hash', models.IntegerField()),
                ('is_instance_item', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DlohUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bungie_id', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loadout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LoadoutInv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DLOHapi.destinyinventoryitems')),
                ('loadout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DLOHapi.loadout')),
            ],
        ),
        migrations.AddField(
            model_name='loadout',
            name='destiny_items_list',
            field=models.ManyToManyField(related_name='loadouts_list', through='DLOHapi.LoadoutInv', to='DLOHapi.DestinyInventoryItems'),
        ),
        migrations.AddField(
            model_name='loadout',
            name='dloh_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DLOHapi.dlohuser'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dloh_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DLOHapi.dlohuser')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DLOHapi.destinyinventoryitems')),
            ],
        ),
    ]
