# Generated by Django 3.2.9 on 2021-12-06 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BungieApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.IntegerField()),
                ('membership_id', models.CharField(max_length=50)),
                ('character_id', models.CharField(max_length=50)),
                ('item_instance_id', models.CharField(max_length=60)),
                ('item_hash', models.IntegerField()),
                ('bucket_hash', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DlohUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('bungie_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DLOHapi.bungieapi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loadout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dloh_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DLOHapi.dlohuser')),
            ],
        ),
        migrations.CreateModel(
            name='LoadoutInv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DLOHapi.bungieapi')),
                ('loadout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DLOHapi.loadout')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dloh_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DLOHapi.dlohuser')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DLOHapi.bungieapi')),
            ],
        ),
    ]
