# Generated by Django 3.2.10 on 2021-12-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DLOHapi', '0002_remove_destinyinventoryitems_flavor_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinyinventoryitems',
            name='bucket_hash',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='destinyinventoryitems',
            name='item_hash',
            field=models.BigIntegerField(),
        ),
    ]
